version: "3.8"
services:
  web:
    build:
      context: ../ui/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: baymax-ui
    stdin_open: true
    volumes:
      - ../UI/:/app
      - /app/node_modules
    networks:
      - default
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:9000:9000"
    container_name: baymax-api
    volumes:
      - ./web:/api
    networks:
      - default
